<?php

declare(strict_types=1);

namespace Aybarsm\Podman\Api\Resources;

use Aybarsm\Podman\Api\Dto\Quadlet\QuadletInstallReport;
use Aybarsm\Podman\Api\Dto\Quadlet\QuadletRemoveOptions;
use Aybarsm\Podman\Api\Dto\Quadlet\QuadletRemoveReport;
use Aybarsm\Podman\Api\Dto\Quadlet\QuadletSummary;
use Aybarsm\Podman\Api\Dto\Shared\Filters;
use Aybarsm\Podman\Api\Exceptions\BadRequestException;
use Aybarsm\Podman\Api\Exceptions\NotFoundException;
use Aybarsm\Podman\Api\Internal\Operation;
use Aybarsm\Podman\Api\Internal\Support\Data;
use Psr\Http\Message\StreamInterface;

/**
 * Libpod `quadlets` operations (systemd units generated by Podman, `podman quadlet`).
 */
final readonly class Quadlets extends AbstractResource
{
    /**
     * List installed quadlets (`podman quadlet list`).
     *
     * @param Filters|null $filters name, pod (pod: spec 5.8+)
     *
     * @return list<QuadletSummary>
     *
     * @since Podman 5.7
     */
    public function list(?Filters $filters = null): array
    {
        $result = $this->transport->send(Operation::QuadletList, query: ['filters' => $filters]);

        return Data::listOf($result->jsonList(), QuadletSummary::fromArray(...));
    }

    /**
     * @param string $name quadlet file name with extension, e.g. "myapp.container"
     *
     * @since Podman 5.8
     */
    public function exists(string $name): bool
    {
        return $this->probe(Operation::QuadletExists, ['name' => $name]);
    }

    /**
     * The quadlet file's contents, comments included (`podman quadlet print`).
     *
     * @param string $name quadlet file name with extension, e.g. "myapp.container"
     *
     * @since Podman 5.8
     *
     * @throws NotFoundException
     */
    public function print(string $name): string
    {
        return $this->transport->send(Operation::QuadletFile, ['name' => $name])->text();
    }

    /**
     * Install a quadlet application (`podman quadlet install`) from a tar archive holding one quadlet file and,
     * optionally, supporting files (Containerfile, kube YAML, configuration).
     *
     * @param bool      $replace       overwrite files that already exist
     * @param bool|null $reloadSystemd reload systemd afterwards (spec default true)
     *
     * @since Podman 5.8
     *
     * @throws BadRequestException
     */
    public function install(StreamInterface|string $tar, bool $replace = false, ?bool $reloadSystemd = null): QuadletInstallReport
    {
        $result = $this->transport->send(
            Operation::QuadletInstall,
            query: ['replace' => $replace ?: null, 'reload-systemd' => $reloadSystemd],
            body: $tar,
            contentType: 'application/x-tar',
        );

        return QuadletInstallReport::fromArray($result->jsonObject());
    }

    /**
     * Remove a quadlet (`podman quadlet rm`).
     *
     * @param string $name quadlet file name with extension, e.g. "myapp.container"
     *
     * @since Podman 5.8
     *
     * @throws BadRequestException
     * @throws NotFoundException
     */
    public function remove(string $name, ?QuadletRemoveOptions $options = null): QuadletRemoveReport
    {
        $result = $this->transport->send(Operation::QuadletDelete, ['name' => $name], $options?->toQuery() ?? []);

        return QuadletRemoveReport::fromArray($result->jsonObject());
    }

    /**
     * Remove several quadlets, or all of the current user's (`podman quadlet rm a b`, `podman quadlet rm --all`).
     *
     * @param list<string> $quadlets file names with extension; required unless $all is true
     *
     * @since Podman 5.8
     *
     * @throws BadRequestException
     */
    public function removeMany(array $quadlets = [], bool $all = false, ?QuadletRemoveOptions $options = null): QuadletRemoveReport
    {
        $result = $this->transport->send(
            Operation::QuadletDeleteAll,
            query: ['quadlets' => $quadlets === [] ? null : $quadlets, 'all' => $all ?: null, ...($options?->toQuery() ?? [])],
        );

        return QuadletRemoveReport::fromArray($result->jsonObject());
    }
}
