<?php

declare(strict_types=1);

namespace Aybarsm\Podman\Api\Dev\Generator;

use Aybarsm\Podman\Api\Dev\Spec\Spec;
use Aybarsm\Podman\Api\Dev\Spec\SpecOperation;
use Aybarsm\Podman\Api\Enums\ApiVersion;
use RuntimeException;

/**
 * Emits src/Internal/Operation.php: the single registry mapping Libpod operationIds to route + minimum version.
 */
final class OperationEnumGenerator
{
    public const string TARGET = 'src/Internal/Operation.php';

    /**
     * @param array<string, string> $since operationId => first spec version
     */
    public static function generate(Spec $latest, array $since, string $floorVersion): string
    {
        $ops = array_values($latest->libpodOperations());
        usort($ops, static fn (SpecOperation $a, SpecOperation $b): int => strcmp($a->caseName(), $b->caseName()));

        self::assertUniqueCaseNames($ops);
        self::assertApiVersionCase($floorVersion);

        $cases = [];
        $byMethod = [];
        $paths = [];
        $byVersion = [];
        $unversioned = [];

        foreach ($ops as $op) {
            $case = $op->caseName();
            $cases[] = sprintf("    case %s = '%s';", $case, $op->id);
            $byMethod[ucfirst(strtolower($op->method))][] = $case;
            $paths[] = sprintf("            self::%s => '%s',", $case, $op->path);

            if (preg_match('/\bnot versioned\b/i', $op->description) === 1) {
                $unversioned[] = $case;
            }

            $version = $since[$op->id] ?? $floorVersion;
            if ($version !== $floorVersion) {
                self::assertApiVersionCase($version);
                $byVersion[$version][] = $case;
            }
        }

        ksort($byMethod);
        uksort($byVersion, static fn (string $a, string $b): int => version_compare($a, $b));

        $methodArms = [];
        foreach ($byMethod as $method => $list) {
            $methodArms[] = self::arm($list, "HttpMethod::{$method}");
        }

        $versionArms = [];
        foreach ($byVersion as $version => $list) {
            $versionArms[] = self::arm($list, 'ApiVersion::'.self::versionCase($version));
        }
        $versionArms[] = '            default => ApiVersion::'.self::versionCase($floorVersion).',';

        $source = 'resources/podman/swagger-v'.$latest->version.'.yaml';

        $template = <<<PHP
            <?php

            declare(strict_types=1);

            namespace Aybarsm\\Podman\\Api\\Internal;

            use Aybarsm\\Podman\\Api\\Enums\\ApiVersion;
            use Aybarsm\\Podman\\Api\\Internal\\Transport\\HttpMethod;

            /**
             * Registry of every Libpod operation in {$source}.
             *
             * GENERATED by `bin/spec operation-enum`. Do not edit by hand: re-run the command instead.
             *
             * @internal
             */
            enum Operation: string
            {
            %CASES%

                public function method(): HttpMethod
                {
                    return match (\$this) {
            %METHODS%
                    };
                }

                public function path(): string
                {
                    return match (\$this) {
            %PATHS%
                    };
                }

                /**
                 * False for routes the spec documents as "not versioned" (served without the /v{version} prefix).
                 */
                public function isVersioned(): bool
                {
                    return match (\$this) {
            %UNVERSIONED%
                    };
                }

                /**
                 * Oldest Podman API version that exposes this operation.
                 */
                public function since(): ApiVersion
                {
                    return match (\$this) {
            %VERSIONS%
                    };
                }
            }

            PHP;

        return strtr($template, [
            '%CASES%' => implode("\n", $cases),
            '%METHODS%' => implode("\n", $methodArms),
            '%PATHS%' => implode("\n", $paths),
            '%VERSIONS%' => implode("\n", $versionArms),
            '%UNVERSIONED%' => implode("\n", [
                ...($unversioned === [] ? [] : [self::arm($unversioned, 'false')]),
                '            default => true,',
            ]),
        ]);
    }

    public static function versionCase(string $specVersion): string
    {
        return 'V'.str_replace('.', '_', $specVersion);
    }

    /**
     * @param list<string> $cases
     */
    private static function arm(array $cases, string $result): string
    {
        $lines = array_map(static fn (string $c): string => "            self::{$c}", $cases);

        return implode(",\n", $lines)." => {$result},";
    }

    /**
     * @param list<SpecOperation> $ops
     */
    private static function assertUniqueCaseNames(array $ops): void
    {
        $seen = [];
        foreach ($ops as $op) {
            $case = $op->caseName();
            if (isset($seen[$case])) {
                throw new RuntimeException("Case name collision: {$case} ({$seen[$case]} vs {$op->id})");
            }
            $seen[$case] = $op->id;
        }
    }

    private static function assertApiVersionCase(string $specVersion): void
    {
        if (ApiVersion::tryFrom($specVersion.'.0') === null) {
            throw new RuntimeException(sprintf(
                'ApiVersion has no case for spec v%s. Add `case %s = \'%s.0\';` to src/Enums/ApiVersion.php first.',
                $specVersion,
                self::versionCase($specVersion),
                $specVersion,
            ));
        }
    }
}
