<?php

declare(strict_types=1);

namespace Aybarsm\Podman\Api\Internal;

use Aybarsm\Podman\Api\Enums\ApiVersion;
use Aybarsm\Podman\Api\Internal\Transport\HttpMethod;

/**
 * Registry of every Libpod operation in resources/podman/swagger-v5.8.yaml.
 *
 * GENERATED by `bin/spec operation-enum`. Do not edit by hand: re-run the command instead.
 *
 * @internal
 */
enum Operation: string
{
    case ArtifactAdd = 'ArtifactAddLibpod';
    case ArtifactDelete = 'ArtifactDeleteLibpod';
    case ArtifactDeleteAll = 'ArtifactDeleteAllLibpod';
    case ArtifactExtract = 'ArtifactExtractLibpod';
    case ArtifactInspect = 'ArtifactInspectLibpod';
    case ArtifactList = 'ArtifactListLibpod';
    case ArtifactLocal = 'ArtifactLocalLibpod';
    case ArtifactPull = 'ArtifactPullLibpod';
    case ArtifactPush = 'ArtifactPushLibpod';
    case ContainerArchive = 'ContainerArchiveLibpod';
    case ContainerAttach = 'ContainerAttachLibpod';
    case ContainerChanges = 'ContainerChangesLibpod';
    case ContainerCheckpoint = 'ContainerCheckpointLibpod';
    case ContainerCreate = 'ContainerCreateLibpod';
    case ContainerDelete = 'ContainerDeleteLibpod';
    case ContainerExec = 'ContainerExecLibpod';
    case ContainerExists = 'ContainerExistsLibpod';
    case ContainerExport = 'ContainerExportLibpod';
    case ContainerHealthcheck = 'ContainerHealthcheckLibpod';
    case ContainerInit = 'ContainerInitLibpod';
    case ContainerInspect = 'ContainerInspectLibpod';
    case ContainerKill = 'ContainerKillLibpod';
    case ContainerList = 'ContainerListLibpod';
    case ContainerLogs = 'ContainerLogsLibpod';
    case ContainerMount = 'ContainerMountLibpod';
    case ContainerPause = 'ContainerPauseLibpod';
    case ContainerPrune = 'ContainerPruneLibpod';
    case ContainerRename = 'ContainerRenameLibpod';
    case ContainerResize = 'ContainerResizeLibpod';
    case ContainerRestart = 'ContainerRestartLibpod';
    case ContainerRestore = 'ContainerRestoreLibpod';
    case ContainerShowMounted = 'ContainerShowMountedLibpod';
    case ContainerStart = 'ContainerStartLibpod';
    case ContainerStats = 'ContainerStatsLibpod';
    case ContainerStop = 'ContainerStopLibpod';
    case ContainerTop = 'ContainerTopLibpod';
    case ContainerUnmount = 'ContainerUnmountLibpod';
    case ContainerUnpause = 'ContainerUnpauseLibpod';
    case ContainerUpdate = 'ContainerUpdateLibpod';
    case ContainerWait = 'ContainerWaitLibpod';
    case ContainersStatsAll = 'ContainersStatsAllLibpod';
    case ExecInspect = 'ExecInspectLibpod';
    case ExecResize = 'ExecResizeLibpod';
    case ExecStart = 'ExecStartLibpod';
    case GenerateKube = 'GenerateKubeLibpod';
    case GenerateSystemd = 'GenerateSystemdLibpod';
    case ImageBuild = 'ImageBuildLibpod';
    case ImageChanges = 'ImageChangesLibpod';
    case ImageCommit = 'ImageCommitLibpod';
    case ImageDelete = 'ImageDeleteLibpod';
    case ImageDeleteAll = 'ImageDeleteAllLibpod';
    case ImageExists = 'ImageExistsLibpod';
    case ImageExport = 'ImageExportLibpod';
    case ImageGet = 'ImageGetLibpod';
    case ImageHistory = 'ImageHistoryLibpod';
    case ImageImport = 'ImageImportLibpod';
    case ImageInspect = 'ImageInspectLibpod';
    case ImageList = 'ImageListLibpod';
    case ImageLoad = 'ImageLoadLibpod';
    case ImagePrune = 'ImagePruneLibpod';
    case ImagePull = 'ImagePullLibpod';
    case ImagePush = 'ImagePushLibpod';
    case ImageResolve = 'ImageResolveLibpod';
    case ImageScp = 'ImageScpLibpod';
    case ImageSearch = 'ImageSearchLibpod';
    case ImageTag = 'ImageTagLibpod';
    case ImageTree = 'ImageTreeLibpod';
    case ImageUntag = 'ImageUntagLibpod';
    case KubeApply = 'KubeApplyLibpod';
    case LocalBuild = 'LocalBuildLibpod';
    case LocalImages = 'LocalImagesLibpod';
    case ManifestAdd = 'ManifestAddLibpod';
    case ManifestCreate = 'ManifestCreateLibpod';
    case ManifestDelete = 'ManifestDeleteLibpod';
    case ManifestExists = 'ManifestExistsLibpod';
    case ManifestInspect = 'ManifestInspectLibpod';
    case ManifestModify = 'ManifestModifyLibpod';
    case ManifestPush = 'ManifestPushLibpod';
    case ManifestPushV3 = 'ManifestPushV3Libpod';
    case NetworkConnect = 'NetworkConnectLibpod';
    case NetworkCreate = 'NetworkCreateLibpod';
    case NetworkDelete = 'NetworkDeleteLibpod';
    case NetworkDisconnect = 'NetworkDisconnectLibpod';
    case NetworkExists = 'NetworkExistsLibpod';
    case NetworkInspect = 'NetworkInspectLibpod';
    case NetworkList = 'NetworkListLibpod';
    case NetworkPrune = 'NetworkPruneLibpod';
    case NetworkUpdate = 'NetworkUpdateLibpod';
    case PlayKube = 'PlayKubeLibpod';
    case PlayKubeDown = 'PlayKubeDownLibpod';
    case PodCreate = 'PodCreateLibpod';
    case PodDelete = 'PodDeleteLibpod';
    case PodExists = 'PodExistsLibpod';
    case PodInspect = 'PodInspectLibpod';
    case PodKill = 'PodKillLibpod';
    case PodList = 'PodListLibpod';
    case PodPause = 'PodPauseLibpod';
    case PodPrune = 'PodPruneLibpod';
    case PodRestart = 'PodRestartLibpod';
    case PodStart = 'PodStartLibpod';
    case PodStatsAll = 'PodStatsAllLibpod';
    case PodStop = 'PodStopLibpod';
    case PodTop = 'PodTopLibpod';
    case PodUnpause = 'PodUnpauseLibpod';
    case PutContainerArchive = 'PutContainerArchiveLibpod';
    case QuadletDelete = 'QuadletDeleteLibpod';
    case QuadletDeleteAll = 'QuadletDeleteAllLibpod';
    case QuadletExists = 'QuadletExistsLibpod';
    case QuadletFile = 'QuadletFileLibpod';
    case QuadletInstall = 'QuadletInstallLibpod';
    case QuadletList = 'QuadletListLibpod';
    case SecretCreate = 'SecretCreateLibpod';
    case SecretDelete = 'SecretDeleteLibpod';
    case SecretExists = 'SecretExistsLibpod';
    case SecretInspect = 'SecretInspectLibpod';
    case SecretList = 'SecretListLibpod';
    case SystemCheck = 'SystemCheckLibpod';
    case SystemDataUsage = 'SystemDataUsageLibpod';
    case SystemEvents = 'SystemEventsLibpod';
    case SystemInfo = 'SystemInfoLibpod';
    case SystemPing = 'SystemPing';
    case SystemPrune = 'SystemPruneLibpod';
    case SystemVersion = 'SystemVersionLibpod';
    case VolumeCreate = 'VolumeCreateLibpod';
    case VolumeDelete = 'VolumeDeleteLibpod';
    case VolumeExists = 'VolumeExistsLibpod';
    case VolumeExport = 'VolumeExportLibpod';
    case VolumeImport = 'VolumeImportLibpod';
    case VolumeInspect = 'VolumeInspectLibpod';
    case VolumeList = 'VolumeListLibpod';
    case VolumePrune = 'VolumePruneLibpod';

    public function method(): HttpMethod
    {
        return match ($this) {
            self::ArtifactDelete,
            self::ArtifactDeleteAll,
            self::ContainerDelete,
            self::ImageDelete,
            self::ImageDeleteAll,
            self::ManifestDelete,
            self::NetworkDelete,
            self::PlayKubeDown,
            self::PodDelete,
            self::QuadletDelete,
            self::QuadletDeleteAll,
            self::SecretDelete,
            self::VolumeDelete => HttpMethod::Delete,
            self::ArtifactExtract,
            self::ArtifactInspect,
            self::ArtifactList,
            self::ContainerArchive,
            self::ContainerChanges,
            self::ContainerExists,
            self::ContainerExport,
            self::ContainerHealthcheck,
            self::ContainerInspect,
            self::ContainerList,
            self::ContainerLogs,
            self::ContainerShowMounted,
            self::ContainerStats,
            self::ContainerTop,
            self::ContainersStatsAll,
            self::ExecInspect,
            self::GenerateKube,
            self::GenerateSystemd,
            self::ImageChanges,
            self::ImageExists,
            self::ImageExport,
            self::ImageGet,
            self::ImageHistory,
            self::ImageInspect,
            self::ImageList,
            self::ImageResolve,
            self::ImageSearch,
            self::ImageTree,
            self::ManifestExists,
            self::ManifestInspect,
            self::NetworkExists,
            self::NetworkInspect,
            self::NetworkList,
            self::PodExists,
            self::PodInspect,
            self::PodList,
            self::PodStatsAll,
            self::PodTop,
            self::QuadletExists,
            self::QuadletFile,
            self::QuadletList,
            self::SecretExists,
            self::SecretInspect,
            self::SecretList,
            self::SystemDataUsage,
            self::SystemEvents,
            self::SystemInfo,
            self::SystemPing,
            self::SystemVersion,
            self::VolumeExists,
            self::VolumeExport,
            self::VolumeInspect,
            self::VolumeList => HttpMethod::Get,
            self::ArtifactAdd,
            self::ArtifactLocal,
            self::ArtifactPull,
            self::ArtifactPush,
            self::ContainerAttach,
            self::ContainerCheckpoint,
            self::ContainerCreate,
            self::ContainerExec,
            self::ContainerInit,
            self::ContainerKill,
            self::ContainerMount,
            self::ContainerPause,
            self::ContainerPrune,
            self::ContainerRename,
            self::ContainerResize,
            self::ContainerRestart,
            self::ContainerRestore,
            self::ContainerStart,
            self::ContainerStop,
            self::ContainerUnmount,
            self::ContainerUnpause,
            self::ContainerUpdate,
            self::ContainerWait,
            self::ExecResize,
            self::ExecStart,
            self::ImageBuild,
            self::ImageCommit,
            self::ImageImport,
            self::ImageLoad,
            self::ImagePrune,
            self::ImagePull,
            self::ImagePush,
            self::ImageScp,
            self::ImageTag,
            self::ImageUntag,
            self::KubeApply,
            self::LocalBuild,
            self::LocalImages,
            self::ManifestAdd,
            self::ManifestCreate,
            self::ManifestPush,
            self::ManifestPushV3,
            self::NetworkConnect,
            self::NetworkCreate,
            self::NetworkDisconnect,
            self::NetworkPrune,
            self::NetworkUpdate,
            self::PlayKube,
            self::PodCreate,
            self::PodKill,
            self::PodPause,
            self::PodPrune,
            self::PodRestart,
            self::PodStart,
            self::PodStop,
            self::PodUnpause,
            self::QuadletInstall,
            self::SecretCreate,
            self::SystemCheck,
            self::SystemPrune,
            self::VolumeCreate,
            self::VolumeImport,
            self::VolumePrune => HttpMethod::Post,
            self::ManifestModify,
            self::PutContainerArchive => HttpMethod::Put,
        };
    }

    public function path(): string
    {
        return match ($this) {
            self::ArtifactAdd => '/libpod/artifacts/add',
            self::ArtifactDelete => '/libpod/artifacts/{name}',
            self::ArtifactDeleteAll => '/libpod/artifacts/remove',
            self::ArtifactExtract => '/libpod/artifacts/{name}/extract',
            self::ArtifactInspect => '/libpod/artifacts/{name}/json',
            self::ArtifactList => '/libpod/artifacts/json',
            self::ArtifactLocal => '/libpod/artifacts/local/add',
            self::ArtifactPull => '/libpod/artifacts/pull',
            self::ArtifactPush => '/libpod/artifacts/{name}/push',
            self::ContainerArchive => '/libpod/containers/{name}/archive',
            self::ContainerAttach => '/libpod/containers/{name}/attach',
            self::ContainerChanges => '/libpod/containers/{name}/changes',
            self::ContainerCheckpoint => '/libpod/containers/{name}/checkpoint',
            self::ContainerCreate => '/libpod/containers/create',
            self::ContainerDelete => '/libpod/containers/{name}',
            self::ContainerExec => '/libpod/containers/{name}/exec',
            self::ContainerExists => '/libpod/containers/{name}/exists',
            self::ContainerExport => '/libpod/containers/{name}/export',
            self::ContainerHealthcheck => '/libpod/containers/{name}/healthcheck',
            self::ContainerInit => '/libpod/containers/{name}/init',
            self::ContainerInspect => '/libpod/containers/{name}/json',
            self::ContainerKill => '/libpod/containers/{name}/kill',
            self::ContainerList => '/libpod/containers/json',
            self::ContainerLogs => '/libpod/containers/{name}/logs',
            self::ContainerMount => '/libpod/containers/{name}/mount',
            self::ContainerPause => '/libpod/containers/{name}/pause',
            self::ContainerPrune => '/libpod/containers/prune',
            self::ContainerRename => '/libpod/containers/{name}/rename',
            self::ContainerResize => '/libpod/containers/{name}/resize',
            self::ContainerRestart => '/libpod/containers/{name}/restart',
            self::ContainerRestore => '/libpod/containers/{name}/restore',
            self::ContainerShowMounted => '/libpod/containers/showmounted',
            self::ContainerStart => '/libpod/containers/{name}/start',
            self::ContainerStats => '/libpod/containers/{name}/stats',
            self::ContainerStop => '/libpod/containers/{name}/stop',
            self::ContainerTop => '/libpod/containers/{name}/top',
            self::ContainerUnmount => '/libpod/containers/{name}/unmount',
            self::ContainerUnpause => '/libpod/containers/{name}/unpause',
            self::ContainerUpdate => '/libpod/containers/{name}/update',
            self::ContainerWait => '/libpod/containers/{name}/wait',
            self::ContainersStatsAll => '/libpod/containers/stats',
            self::ExecInspect => '/libpod/exec/{id}/json',
            self::ExecResize => '/libpod/exec/{id}/resize',
            self::ExecStart => '/libpod/exec/{id}/start',
            self::GenerateKube => '/libpod/generate/kube',
            self::GenerateSystemd => '/libpod/generate/{name}/systemd',
            self::ImageBuild => '/libpod/build',
            self::ImageChanges => '/libpod/images/{name}/changes',
            self::ImageCommit => '/libpod/commit',
            self::ImageDelete => '/libpod/images/{name}',
            self::ImageDeleteAll => '/libpod/images/remove',
            self::ImageExists => '/libpod/images/{name}/exists',
            self::ImageExport => '/libpod/images/export',
            self::ImageGet => '/libpod/images/{name}/get',
            self::ImageHistory => '/libpod/images/{name}/history',
            self::ImageImport => '/libpod/images/import',
            self::ImageInspect => '/libpod/images/{name}/json',
            self::ImageList => '/libpod/images/json',
            self::ImageLoad => '/libpod/images/load',
            self::ImagePrune => '/libpod/images/prune',
            self::ImagePull => '/libpod/images/pull',
            self::ImagePush => '/libpod/images/{name}/push',
            self::ImageResolve => '/libpod/images/{name}/resolve',
            self::ImageScp => '/libpod/images/scp/{name}',
            self::ImageSearch => '/libpod/images/search',
            self::ImageTag => '/libpod/images/{name}/tag',
            self::ImageTree => '/libpod/images/{name}/tree',
            self::ImageUntag => '/libpod/images/{name}/untag',
            self::KubeApply => '/libpod/kube/apply',
            self::LocalBuild => '/libpod/local/build',
            self::LocalImages => '/libpod/local/images/load',
            self::ManifestAdd => '/libpod/manifests/{name}/add',
            self::ManifestCreate => '/libpod/manifests/{name}',
            self::ManifestDelete => '/libpod/manifests/{name}',
            self::ManifestExists => '/libpod/manifests/{name}/exists',
            self::ManifestInspect => '/libpod/manifests/{name}/json',
            self::ManifestModify => '/libpod/manifests/{name}',
            self::ManifestPush => '/libpod/manifests/{name}/registry/{destination}',
            self::ManifestPushV3 => '/libpod/manifests/{name}/push',
            self::NetworkConnect => '/libpod/networks/{name}/connect',
            self::NetworkCreate => '/libpod/networks/create',
            self::NetworkDelete => '/libpod/networks/{name}',
            self::NetworkDisconnect => '/libpod/networks/{name}/disconnect',
            self::NetworkExists => '/libpod/networks/{name}/exists',
            self::NetworkInspect => '/libpod/networks/{name}/json',
            self::NetworkList => '/libpod/networks/json',
            self::NetworkPrune => '/libpod/networks/prune',
            self::NetworkUpdate => '/libpod/networks/{name}/update',
            self::PlayKube => '/libpod/play/kube',
            self::PlayKubeDown => '/libpod/play/kube',
            self::PodCreate => '/libpod/pods/create',
            self::PodDelete => '/libpod/pods/{name}',
            self::PodExists => '/libpod/pods/{name}/exists',
            self::PodInspect => '/libpod/pods/{name}/json',
            self::PodKill => '/libpod/pods/{name}/kill',
            self::PodList => '/libpod/pods/json',
            self::PodPause => '/libpod/pods/{name}/pause',
            self::PodPrune => '/libpod/pods/prune',
            self::PodRestart => '/libpod/pods/{name}/restart',
            self::PodStart => '/libpod/pods/{name}/start',
            self::PodStatsAll => '/libpod/pods/stats',
            self::PodStop => '/libpod/pods/{name}/stop',
            self::PodTop => '/libpod/pods/{name}/top',
            self::PodUnpause => '/libpod/pods/{name}/unpause',
            self::PutContainerArchive => '/libpod/containers/{name}/archive',
            self::QuadletDelete => '/libpod/quadlets/{name}',
            self::QuadletDeleteAll => '/libpod/quadlets',
            self::QuadletExists => '/libpod/quadlets/{name}/exists',
            self::QuadletFile => '/libpod/quadlets/{name}/file',
            self::QuadletInstall => '/libpod/quadlets',
            self::QuadletList => '/libpod/quadlets/json',
            self::SecretCreate => '/libpod/secrets/create',
            self::SecretDelete => '/libpod/secrets/{name}',
            self::SecretExists => '/libpod/secrets/{name}/exists',
            self::SecretInspect => '/libpod/secrets/{name}/json',
            self::SecretList => '/libpod/secrets/json',
            self::SystemCheck => '/libpod/system/check',
            self::SystemDataUsage => '/libpod/system/df',
            self::SystemEvents => '/libpod/events',
            self::SystemInfo => '/libpod/info',
            self::SystemPing => '/libpod/_ping',
            self::SystemPrune => '/libpod/system/prune',
            self::SystemVersion => '/libpod/version',
            self::VolumeCreate => '/libpod/volumes/create',
            self::VolumeDelete => '/libpod/volumes/{name}',
            self::VolumeExists => '/libpod/volumes/{name}/exists',
            self::VolumeExport => '/libpod/volumes/{name}/export',
            self::VolumeImport => '/libpod/volumes/{name}/import',
            self::VolumeInspect => '/libpod/volumes/{name}/json',
            self::VolumeList => '/libpod/volumes/json',
            self::VolumePrune => '/libpod/volumes/prune',
        };
    }

    /**
     * False for routes the spec documents as "not versioned" (served without the /v{version} prefix).
     */
    public function isVersioned(): bool
    {
        return match ($this) {
            self::SystemPing => false,
            default => true,
        };
    }

    /**
     * Oldest Podman API version that exposes this operation.
     */
    public function since(): ApiVersion
    {
        return match ($this) {
            self::ArtifactAdd,
            self::ArtifactDelete,
            self::ArtifactExtract,
            self::ArtifactInspect,
            self::ArtifactList,
            self::ArtifactPull,
            self::ArtifactPush,
            self::VolumeExport,
            self::VolumeImport => ApiVersion::V5_6,
            self::ArtifactDeleteAll,
            self::LocalBuild,
            self::LocalImages,
            self::QuadletList => ApiVersion::V5_7,
            self::ArtifactLocal,
            self::QuadletDelete,
            self::QuadletDeleteAll,
            self::QuadletExists,
            self::QuadletFile,
            self::QuadletInstall => ApiVersion::V5_8,
            default => ApiVersion::V5_4,
        };
    }
}
